remote_theme: "mmistakes/minimal-mistakes@4.26.2"

title: "Alioune Badara Seye - Portfolio IT"
description: "Labs réseau, DevSecOps & Support technique"
author: "Alioune Badara Seye"

# Pas besoin de plugins complexes pour commencer
plugins:
  - jekyll-remote-theme

# Configuration du thème
minimal_mistakes_skin: "default" # ou "dark", "air", "contrast"
search: true
